require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TasksController do
  let!(:user){ FactoryGirl.create(:user) }
  let!(:project){ FactoryGirl.create(:project, user: user, name: 'project 1') }
  let!(:task){ FactoryGirl.create(:task, project: project, name: 'task 1') }
  before(:each) do
    sign_in :user, user
  end

  # This should return the minimal set of attributes required to create a valid
  # Task. As you add validations to Task, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "project_id" => project.to_param, "name" => "my task" }
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Task" do
        expect {
          post :create, task: valid_attributes, format: :js
        }.to change(Task, :count).by(1)
      end

      it "assigns a newly created task as @task" do
        post :create, task: valid_attributes, format: :js
        assigns(:task).should be_a(Task)
        assigns(:task).should be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved task as @task" do
        # Trigger the behavior that occurs when invalid params are submitted
        Task.any_instance.stub(:save).and_return(false)
        post :create, task: { "project_id" => project.to_param, "name" => "invalid value" }, format: :js
        assigns(:task).should be_a_new(Task)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested task" do
        # Assuming there are no other tasks in the database, this
        # specifies that the Task created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Task.any_instance.should_receive(:update_attributes).with({ "project_id" => project.to_param, "name" => "buy an elephant" })
        put :update, id: task.to_param, :task => { "project_id" => project.to_param, "name" => "buy an elephant" }, format: :js
      end

      it "assigns the requested task as @task" do
        put :update, id: task.to_param, task: valid_attributes, format: :js
        assigns(:task).should eq(task)
      end
    end

    describe "with invalid params" do
      it "assigns the task as @task" do
        # Trigger the behavior that occurs when invalid params are submitted
        Task.any_instance.stub(:save).and_return(false)
        put :update, id: task.to_param, task: { "project_id" => project.to_param, "name" => "invalid value" }, format: :js
        assigns(:task).should eq(task)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested task" do
      expect {
        delete :destroy, id: task.to_param, format: :js
      }.to change(Task, :count).by(-1)
    end
  end
end
